[project]
name = "connectify-rs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "playwright>=1.52.0",
    "pytest>=8.3.5",
]
