# Only apply these settings when cross-compiling from non-Linux hosts
# Not needed anymore we made the comprehensive cross_build_on_mac.sh
[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"
# Only apply these settings when cross-compiling from non-Linux hosts
#[target.x86_64-unknown-linux-gnu]
#linker = "./cargo-linker"

#[target.aarch64-unknown-linux-gnu]
#linker = "aarch64-elf-gcc"
#
#[target.x86_64-unknown-freebsd]
#linker = "x86_64-unknown-freebsd13-clang"
#rustflags = [
#    "-C", "link-arg=--sysroot=~/freebsd-sysroot",
#]

#[target.aarch64-pc-windows-msvc]
#linker = "lld-link"
#rustflags = [
#    "-C", "link-arg=/LIBPATH:/Users/htr/opt/aarch64-windows/lib/um/arm64",
#    "-C", "link-arg=/LIBPATH:/Users/htr/opt/aarch64-windows/lib/ucrt/arm64/",
#    "-C", "link-arg=/LIBPATH:/Users/htr/opt/aarch64-windows/lib/arm64",
#    "-C", "link-arg=/LIBPATH:/Users/htr/opt/aarch64-windows/lib/aarch64-windows-msvc/ucrt",
#    "-Lnative=/Users/htr/opt/aarch64-windows/lib/um/arm64",
#    "-Lnative=/Users/htr/opt/aarch64-windows/lib/um/arm64",
#    "-Lnative=/Users/htr/opt/aarch64-windows/ucr"
#]
