server:
  host: "127.0.0.1"
  port: 8086
use_twilio: true
use_stripe: true
use_payrexx: true
use_fulfillment: true
use_gcal: true
use_adhoc_session: true

database:
  url: sqlite://example.db

twilio:
  account_sid: "secret_from_env"
  api_key_sid: "secret_from_env"
  api_key_secret: "secret_from_env"
  verify_service_sid: "secret_from_env"

stripe:
  secret_key: "secret_from_env"
  success_url: "https://example.com/api/stripe/success"
  cancel_url: "https://example.com/api/stripe/cancel"
  payment_success_url: "https://example.com/payment-success.html"
  default_currency: "CHF"
  price_tiers:
    - duration_minutes: 15
      unit_amount: 7000 # 70.00 CHF
      product_name: "Short Call (15 Min)"
    #      currency: "CHF" # optional
    - duration_minutes: 30
      unit_amount: 12000 # 120.00 CHF
      product_name: "Base Call (30 Min)"
    - duration_minutes: 45
      unit_amount: 18000 # 180.00 CHF
      product_name: "Standard Call (45 Min)"
    - duration_minutes: 60
      unit_amount: 25000 # 250.00 CHF
      product_name: "Intense Call (60 Min)"

payrexx:
  api_key: "secret_from_env"
  secret_key: "secret_from_env"
  currency: "EUR"
  instance_name: "My Payrexx Instance"
  success_url: "https://example.com/api/payrexx/success"
  failed_url: "https://example.com/api/payrexx/failed"
  cancel_url: "https://example.com/api/payrexx/cancel"


gcal:
  client_id: "secret_from_env"
  client_secret: "secret_from_env"
  refresh_token: "secret_from_env"
  key_path: "./service_account_key.json"
calendly:
  client_id: "secret_from_env"
  client_secret: "secret_from_env"
  refresh_token: "secret_from_env"
  redirect_uri: "https://example.com/api/calendly/callback"

fulfillment:
  FULFILLMENT_SHARED_SECRET: "secret_from_env"

adhoc_settings:
  admin_enabled: true
  preparation_time_minutes: 120
